## action id. unique (random) number
int64 id
## wall time when this activity started 
time start_wall_time
## wall time when this activity finished
# 0: activity did not finish yet
time finish_wall_time
## ros time when this activity started 
# 0: activity uses wall time
time start_time
## ros time when this activity finished
# 0: activity did not finish yet
time finish_time
## description of the activity
string description
